#ENC[AES256_GCM,data:6PUh0SMeLS8nxfjIYflYdo6AXMoCOypCl3iEKm9XUPXjmkFXqF/KdQ5epNaCxUwJtpv96BZdbA==,iv:u6wD/Ii3UVKVe9ms9it8xBSk7nr9EO2ej4UdGeFylkg=,tag:C4R6Ohq51hDOMQUaXtXlDQ==,type:comment]
secrets:
    sops:
        age_key: ENC[AES256_GCM,data:SHlHHW5yi7mj/cIqkE2v5tVwcNd8dpBKJ6EyXeEwlujClMQBO0PqP8yhPljqqCNtJQqcsU60xHEwXHDOXI19NpMvVBV6+hfGIFoZ2pNZAyR/3LfbA7OmjSpIkh/QDF6AXz7b2U6CaDarQSGfB2RYdP/XfZ8MLzL1pazMtu4TYM40mfeIiFw3Q0Vh+E1oSs6BSgC58IXUbdrlUbvy6R0qDoMii2t9UM1rtt00v8F0frt0Cti3p/prTduPCOtfGrLj1YrvaS7X1icPU6nkpMv9XIBvDtyYfp80BP+qLXBuyUQc+SFQDUJslq1+U+CB0Uo6,iv:lcpacJsq/sD1+c/YUKUwzWVA4hWbZDPCOlIKHS5Sgx8=,tag:HBu1Bw7jY52WbD/qBbVoXA==,type:str]
        registry:
            hostname: ENC[AES256_GCM,data:EtAAsncNRPmo4ZeCFLgEw6TSHR0/hCdg4w==,iv:1Z5heuOD45FBiuradCKAfA3neitS1zS85rCHxTcaZL8=,tag:Gvmgo/x6vfmjdLDsMihfhQ==,type:str]
            username: ENC[AES256_GCM,data:Uy+x5aFP9dpCI+dBKmoXfXc=,iv:oSAh5GmmojAbXMqZiWp8a31qEuZM8r6BfD6kckVu4uY=,tag:6kxS5an7WnepTwBMjHJ/JA==,type:str]
            password: ENC[AES256_GCM,data:s5ADWQz5wmwBVw==,iv:KLUigAlte05EwxFgux+SBmp1jIoqvaZQW1QpzBFzt3g=,tag:a/XjRuz1LImH4b6e1oiFyw==,type:str]
        git:
            basic_auth:
                username: ENC[AES256_GCM,data:sIyc+Qhw,iv:DIbztMNnb4OGVvc4ZOMMoj3uX8IQKpthdnlygt9hq9M=,tag:4qRVTNTG4U93IGxhnwRusA==,type:str]
                password: ENC[AES256_GCM,data:/Pnwh38ZNzTXs6dZngYWwi7ZOWK/QuGASOkFBFHliOzHqLMkSsC7kQ==,iv:BsdF+7dBHx7XBR5jJngFKV7ybD5H/2MJAKE3NeD7wEs=,tag:d23v0Thxmj8TXx5LGwBJFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y042zewxcpn4ch8h6a7r37d8q43t6fwtuzk326vs50ul967qcasse7z5cc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdE1aK2tCdWFJNk1sOUJK
            RVl5RTZUS2poaTFYTGlWZ3o2WHJrOEdsSjA4CmNhZnpKcEVPdHVackpoRzI4TU1i
            c2YvTjZkUHBTdllvQTVkaFBDWFZwOEkKLS0tICs4M2hITjlFRzR0dmRGZVNEbHpQ
            K1NEYStSZW80a0lvQmJVT1lNRGhVSFkKrqYElTlamuHqSvAmG7OhPj8EjRN0AcbI
            CB8LuC+IzPQcyOfEdAmi1FX6fZnEjcUDbyLscYX5EXRm6NvbNCwAIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-02T17:22:42Z"
    mac: ENC[AES256_GCM,data:r4S9K2HEfZ50EVHJdpOx9FjCbu4un1P6s30QgRA1XaNj5wbtmuPvVC2WNB/XoqM9wWLSCKXYzVvKc7CaxOC51+IvB5B4cuV9u1+RDqoLVYB9W6TYblO2811STc3k0QiJDxyTkKaqGHRsQF026wi9HVGs/w7RLbMO8SVvz0Xiqss=,iv:PueE9JwsjSBza2JLYqmwnIqd+WQZPvDd5DzRrvd4Zlw=,tag:6L7ARsF0lHfZumN2AptH/Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
