#ENC[AES256_GCM,data:yN86I150f2aGVXtI3DgtgkdExItJFxuEtPmNovf/cOfxO9q7o/M7T/VkpMzjhX2l/K6ypp4nJQ==,iv:VL7birtFsE1PRn7Fhuw4I94bvlF15iFhsjfVD+d1+M0=,tag:5xnM5+jEbESjFwYuPeLoOQ==,type:comment]
tap_install:
    sensitive_values:
        shared:
            image_registry:
                password: ENC[AES256_GCM,data:kw5VSCuLuGdQI2leHU+JhNVl9Bpoz3OgGL+vprezsFkLKZa1t5NHaE/89qEI/ZCF//AMTQ==,iv:tEAlVHTXa0Xe58BBnxVzsa/Pj7uNF6CYyUA11goWFyQ=,tag:FzFrsvR3YVaxSQ9qxegoUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y042zewxcpn4ch8h6a7r37d8q43t6fwtuzk326vs50ul967qcasse7z5cc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VHVkVXQwWCsvZUYzUk9o
            KzRwTmFzT3JhbGdpOEtHRDNFa3dMWWVsUmdzCkhGOHdCQlV4SHk4NXFldVpjL0lM
            NkZOQWVhUEtzTUsrOXlIQUtzVG85dU0KLS0tIC96aE9NeGFYbGNuZHJ4MFRSN2F4
            ZDBOQzlxeTQrSEZzRzdiQkE5OGJtRWMKGmOxIlnf3tt3m7cRXxjYFYqz4ceRQ2N7
            i74BQTDzTfTTzKCa7JPJcK1whJHitUZxgGIsEOEZ/iw4skLpbRIi9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-02T20:04:18Z"
    mac: ENC[AES256_GCM,data:68wrFs9B1ofkkqYOPz2/07cC9hTH4r7ixDR2X0FKA4ao+eVhsst8Wv+cOiui4CTuq4dZi5gfDYILJjmmcDUNX5g77cljIJSz7RGlkXO7VUbOiNN+J1g1ROInwALGaO4AQDRhuedVWYE2AT/zD5IgFARajjTpoxJfuM3NNubJRGs=,iv:sZJ5B9KaXMWwP8f+aAayg3A1nM9HMBltogNJMZH5zW0=,tag:nahLKNAGURSLpuDdHjPcbw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
